<?php

declare(strict_types=1);
require __DIR__ . DIRECTORY_SEPARATOR . 'config.php';
$user = require_login();
$plans = ['ssc-cgl'=>['SSC CGL Series','ssc-cgl',25000], 'ssc-chsl'=>['SSC CHSL Series','ssc-chsl',25000], 'rrb-ntpc'=>['RRB NTPC Series','rrb-ntpc',25000], 'rrb-group-d'=>['RRB Group D Series','rrb-group-d',25000], 'ibps-po'=>['IBPS PO Series','ibps-po',25000], 'sbi-clerk'=>['SBI Clerk Series','sbi-clerk',25000], 'bpsc-prelims'=>['BPSC Prelims Series','bpsc-prelims',25000], 'state-psc-mains'=>['State PSC Mains Series','state-psc-mains',25000], 'nda-cds'=>['NDA & CDS Series','nda-cds',25000], 'ctet'=>['CTET Series','ctet',25000], 'all-access'=>['All-Access Plan','all-access',99900]];
foreach (series_records() as $record) if (!empty($record['active']) && isset($record['slug'],$record['title'])) $plans[$record['slug']] = [$record['title'].' Series',$record['slug'],25000];
$planKey=(string)($_GET['plan']??$_POST['plan']??'');
if(!isset($plans[$planKey])){header('Location: dashboard.php');exit;}
[$planName,$product,$baseAmount]=$plans[$planKey];
$coupon=$_SESSION['checkout_coupon'][$planKey]??null;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='apply_coupon'){$coupon=valid_coupon((string)($_POST['coupon']??''),$user,$product,$baseAmount);if($coupon===null)$error='Coupon is invalid, expired, restricted or already used.';else$_SESSION['checkout_coupon'][$planKey]=$coupon;}
$amount=is_array($coupon)?(int)$coupon['final_paise']:$baseAmount;
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='demo_pay'){
 $order=['id'=>'DEMO-'.strtoupper(bin2hex(random_bytes(5))),'plan'=>$planKey,'product'=>$product,'amount'=>number_format($amount/100,2,'.',''),'original_amount'=>number_format($baseAmount/100,2,'.',''),'coupon'=>is_array($coupon)?$coupon['code']:null,'discount'=>is_array($coupon)?number_format($coupon['discount_paise']/100,2,'.',''):'0.00','currency'=>'INR','status'=>'paid','provider'=>'demo','created_at'=>date('c')];
 $orders=$user['orders']??[];$orders[]=$order;$enrolled=$user['enrolled']??[];if($product==='all-access')$enrolled=array_values(array_unique(array_merge($enrolled,array_keys($plans))));else$enrolled[]=$product;update_current_user(['orders'=>$orders,'enrolled'=>array_values(array_unique($enrolled))]);
 if(is_array($coupon)){ $all=coupons();foreach($all as &$saved)if(($saved['code']??'')===$coupon['code'])$saved['used']=(int)($saved['used']??0)+1;save_coupons($all); }unset($_SESSION['checkout_coupon'][$planKey]);header('Location: orders.php?paid='.rawurlencode($order['id']));exit;
}
$planEsc=e($planKey);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Checkout | RankSetu</title><style>body{margin:0;min-height:100vh;background:#efece2;font:16px Arial;display:grid;place-items:center;padding:24px;color:#1c1a15}.box{width:min(560px,100%);background:#f8f6ee;border:1px solid #cfc7ac;padding:32px}h1{font:600 2rem Georgia;color:#16233f}.eyebrow{color:#9c3b2e;font-weight:700;font-size:.75rem;text-transform:uppercase}.muted{color:#625e50}.price{font:700 2.4rem Georgia;color:#9c3b2e;margin:20px 0}.notice,.error{padding:14px;margin:18px 0;border-left:4px solid #a97a24;background:#a97a241c;color:#625e50}.error{border-color:#9c3b2e;background:#f7ded8;color:#70251c}.coupon{display:flex;gap:8px;flex-wrap:wrap}.coupon input{flex:1;min-width:180px;padding:12px;border:1px solid #cfc7ac}.btn{border:0;background:#9c3b2e;color:#fff;padding:13px 18px;font-weight:700;cursor:pointer}.back{display:block;margin-top:22px;color:#9c3b2e;text-decoration:none}</style></head><body><main class="box"><div class="eyebrow">Demo checkout</div><h1><?=e($planName)?></h1><p class="muted">Signed in as <?=e($user['email'])?></p><?php if(is_array($coupon)):?><p class="muted">Original: <s>₹<?=number_format($baseAmount/100,2)?></s> &bull; Coupon <strong><?=e($coupon['code'])?></strong> saved ₹<?=number_format($coupon['discount_paise']/100,2)?></p><?php endif;?><div class="price">₹<?=number_format($amount/100,2)?></div><?php if($error):?><div class="error"><?=e($error)?></div><?php endif;?><form method="post" class="coupon"><input type="hidden" name="plan" value="<?=$planEsc?>"><input type="hidden" name="action" value="apply_coupon"><input name="coupon" placeholder="Coupon code" required><button class="btn" type="submit">Apply coupon</button></form><div class="notice"><strong>Demo payment:</strong> no real money is charged. This creates an order and enrolls the student. The coupon discount is stored with the order.</div><form method="post"><input type="hidden" name="plan" value="<?=$planEsc?>"><input type="hidden" name="action" value="demo_pay"><button class="btn" type="submit">Complete demo payment</button></form><a class="back" href="dashboard.php">Back to dashboard</a></main></body></html>
