<?php

declare(strict_types=1);
require __DIR__ . DIRECTORY_SEPARATOR . 'config.php';
$user = require_login();
$catalog = ['ssc-cgl'=>'SSC CGL','ssc-chsl'=>'SSC CHSL','rrb-ntpc'=>'RRB NTPC','rrb-group-d'=>'RRB Group D','ibps-po'=>'IBPS PO','sbi-clerk'=>'SBI Clerk','bpsc-prelims'=>'BPSC Prelims','state-psc-mains'=>'State PSC Mains','nda-cds'=>'NDA & CDS','ctet'=>'CTET'];
foreach (series_records() as $record) if (!empty($record['active']) && isset($record['slug'],$record['title'])) $catalog[$record['slug']]=$record['title'];
$enrolled=array_values(array_intersect(array_keys($catalog),$user['enrolled']??[]));$attempts=array_reverse($user['attempts']??[]);$orders=array_reverse($user['orders']??[]);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard | RankSetu</title><style>body{margin:0;background:#efece2;color:#1c1a15;font:16px Arial}header{background:#16233f;border-bottom:3px solid #a97a24;padding:18px 5%;display:flex;justify-content:space-between;align-items:center}.brand{color:#fff;text-decoration:none;font:700 1.5rem Georgia}.nav{display:flex;gap:18px;align-items:center;flex-wrap:wrap}.nav a,.user{color:#f5ead2;text-decoration:none;font-size:.9rem}.wrap{width:min(1100px,calc(100% - 40px));margin:auto;padding:50px 0}h1,h2{font-family:Georgia;color:#16233f}h1{font-size:clamp(2rem,5vw,3rem)}.stats,.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.stat,.card,.panel{background:#f8f6ee;border:1px solid #cfc7ac;padding:22px}.stat strong{display:block;color:#9c3b2e;font:700 1.8rem Georgia}.stat span,.muted{color:#625e50}.head{display:flex;justify-content:space-between;align-items:end;margin:28px 0 14px}.head a,.meta a{color:#9c3b2e;font-weight:700;text-decoration:none}.card h2{font-size:1.15rem}.card p{color:#625e50;min-height:42px}.meta{font-size:.82rem;color:#625e50;margin:13px 0}.btn{display:inline-block;background:#9c3b2e;color:#fff;text-decoration:none;padding:11px 15px;font-weight:700}.empty{padding:25px;background:#f8f6ee;border:1px dashed #cfc7ac;color:#625e50}.order{display:flex;justify-content:space-between;border-bottom:1px solid #cfc7ac;padding:13px 0}.order small{display:block;color:#625e50;margin-top:4px}@media(max-width:700px){.stats,.grid{grid-template-columns:1fr}.wrap{padding:35px 0}.user{display:none}.order{display:block}.order .btn{margin-top:10px}}
</style></head><body><header><a class="brand" href="index.php">RankSetu</a><nav class="nav"><span class="user"><?=e($user['name'])?></span><?php if(($user['role']??'')==='admin'):?><a href="admin.php">Admin</a><a href="admin-coupons.php">Coupons</a><?php endif;?><a href="index.php">Home</a><a href="history.php">Test history</a><a href="orders.php">Orders</a><a href="logout.php">Log out</a></nav></header><main class="wrap"><h1>Good to see you, <?=e($user['name'])?>.</h1><p class="muted">Your learning, test performance and orders in one place.</p><section class="stats"><div class="stat"><strong><?=count($enrolled)?></strong><span>enrolled series</span></div><div class="stat"><strong><?=count($attempts)?></strong><span>tests attempted</span></div><div class="stat"><strong><?=count($orders)?></strong><span>orders</span></div></section><div class="head"><h2>My learning</h2><a href="index.php#exams">Browse series &rarr;</a></div><?php if(!$enrolled):?><div class="empty">No enrolled series yet. Browse the catalog to begin.</div><?php else:?><section class="grid"><?php foreach($enrolled as $slug):?><article class="card"><h2><?=e($catalog[$slug])?></h2><p>Timed questions with results and saved attempt history.</p><div class="meta">Ready to practice</div><a class="btn" href="practice.php?product=<?=e($slug)?>">Start practice</a></article><?php endforeach;?></section><?php endif;?><section class="panel" style="margin-top:25px"><div class="head"><h2>Order history</h2><a href="orders.php">View all orders &rarr;</a></div><?php if(!$orders):?><div class="empty">No orders yet.</div><?php else:foreach(array_slice($orders,0,3) as $order):?><div class="order"><div><strong><?=e($order['product'])?></strong><small><?=e($order['id'])?> &bull; <?=e(date('d M Y',strtotime($order['created_at'])))?></small></div><a class="btn" href="invoice.php?id=<?=e($order['id'])?>">Download invoice</a></div><?php endforeach;endif;?></section></main></body></html>
