<?php

declare(strict_types=1);
require __DIR__ . DIRECTORY_SEPARATOR . 'config.php';
$user = require_login();
$series = banking_labels();
foreach (series_records() as $record) if (!empty($record['active']) && isset($record['slug'], $record['title'])) $series[$record['slug']] = $record['title'];
$slug = (string) ($_GET['product'] ?? '');
if (!isset($series[$slug]) || !user_has_course_access($user, $slug)) { header('Location: student.php'); exit; }
$tests = test_records($slug);
$attempted = [];
foreach ($user['attempts'] ?? [] as $attempt) if (($attempt['product'] ?? '') === $slug) $attempted[$attempt['test_id']] = $attempt;
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($series[$slug]) ?> practice | RankSetu</title><style>:root{--navy:#16233f;--maroon:#9c3b2e;--paper:#efece2;--card:#f8f6ee;--muted:#625e50;--line:#cfc7ac;--gold:#a97a24}*{box-sizing:border-box}body{margin:0;background:var(--paper);font-family:Arial;color:#1c1a15}header{background:var(--navy);border-bottom:3px solid var(--gold);padding:18px 5%;display:flex;justify-content:space-between}.brand{font:700 1.5rem Georgia;color:#fff;text-decoration:none}.nav a{color:#f5ead2;text-decoration:none;margin-left:18px}.wrap{width:min(1000px,calc(100% - 40px));margin:auto;padding:52px 0}h1,h2{font-family:Georgia;color:var(--navy)}h1{font-size:clamp(2rem,5vw,3rem);margin:8px 0}.muted{color:var(--muted)}.summary{background:var(--navy);color:#fff;padding:24px;margin:24px 0}.summary h2{color:#fff;margin:0 0 8px}.tests{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.test{background:var(--card);border:1px solid var(--line);padding:20px}.test h2{font-size:1.2rem;margin:0 0 7px}.test p{font-size:.88rem;min-height:35px}.meta{color:var(--muted);font-size:.8rem;margin:13px 0}.score{color:#286447;font-weight:700}.btn{display:inline-block;background:var(--maroon);color:#fff;text-decoration:none;padding:11px 15px;font-weight:700;font-size:.86rem}@media(max-width:650px){.tests{grid-template-columns:1fr}.wrap{padding:35px 0}}</style></head>
<body><header><a class="brand" href="index.php">RankSetu</a><nav class="nav"><a href="dashboard.php">Dashboard</a><a href="history.php">History</a><a href="logout.php">Log out</a></nav></header><main class="wrap"><div class="muted">Full-length series</div><h1><?= e($series[$slug]) ?></h1><p class="muted">Complete the tests in sequence. Every test has its own timer, result and attempt history.</p><section class="summary"><h2><?= count($tests) ?> tests available</h2><p>Every question is loaded from the configured test database.</p></section><section class="tests"><?php foreach ($tests as $id => $test): ?><article class="test"><h2><?= e($test['title'] ?? strtoupper($id)) ?></h2><p><?= count($test['questions'] ?? []) ?> questions &bull; <?= e((string) ($test['duration_minutes'] ?? 10)) ?> minutes</p><?php if (isset($attempted[$id])): ?><div class="score">Best saved score: <?= e((string) $attempted[$id]['percentage']) ?>%</div><?php endif; ?><div class="meta">Test <?= e(str_pad(substr($id, 5), 2, '0', STR_PAD_LEFT)) ?> of <?= count($tests) ?></div><a class="btn" href="instructions.php?product=<?= e($slug) ?>&test=<?= e($id) ?>"><?= isset($attempted[$id]) ? 'Reattempt' : 'Read instructions' ?></a></article><?php endforeach; ?></section></main></body></html>
