<?php

declare(strict_types=1);
require __DIR__ . DIRECTORY_SEPARATOR . 'config.php';
$user = current_user();
$plans = subscription_plans(true);
$activeSlugs = [];
if ($user !== null) foreach (user_subscriptions((string)$user['id']) as $subscription) if (subscription_is_current($subscription)) $activeSlugs[] = (string)($subscription['plan_slug'] ?? '');
$catalog = available_course_catalog();
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Subscriptions | <?= e(APP_BRAND_NAME) ?></title><style>
:root{--navy:#16233f;--maroon:#9c3b2e;--paper:#efece2;--card:#f8f6ee;--ink:#1c1a15;--muted:#625e50;--line:#cfc7ac;--gold:#a97a24;--green:#286447}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px Arial,sans-serif}header{background:var(--navy);border-bottom:3px solid var(--gold);padding:18px 5%;display:flex;justify-content:space-between;gap:20px}.brand{color:#fff;text-decoration:none;font:700 1.5rem Georgia,serif}.nav{display:flex;gap:18px;flex-wrap:wrap}.nav a{color:#f5ead2;text-decoration:none}.wrap{width:min(1160px,calc(100% - 36px));margin:auto;padding:54px 0}h1,h2,h3{font-family:Georgia,serif;color:var(--navy)}h1{font-size:clamp(2.2rem,5vw,4rem);margin:0 0 10px}.lede,.muted{color:var(--muted)}.lede{max-width:620px;line-height:1.6}.plans{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px;margin-top:35px}.plan{background:var(--card);border:1px solid var(--line);padding:25px;position:relative}.plan.featured{border:2px solid var(--maroon);transform:translateY(-8px)}.badge{color:var(--maroon);font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.price{font:700 2.5rem Georgia,serif;color:var(--maroon);margin:17px 0 4px}.old{text-decoration:line-through;color:var(--muted);margin-left:8px;font-size:.95rem}.plan ul{list-style:none;padding:0;display:grid;gap:8px;min-height:90px;color:var(--muted)}.plan li::before{content:'✓';color:var(--green);font-weight:700;margin-right:8px}.course-list{margin:12px 0;padding:12px;border:1px solid var(--line);background:#fffdf7}.course-list summary{color:var(--navy);font-size:.86rem;font-weight:700;cursor:pointer}.course-list p{margin:9px 0 0;color:var(--muted);font-size:.82rem;line-height:1.55}.course-count{color:var(--green);font-weight:700}.btn{display:block;text-align:center;background:var(--maroon);color:#fff;text-decoration:none;padding:13px;font-weight:700}.active{background:#e0f0e6;color:var(--green);padding:13px;text-align:center;font-weight:700}.empty{background:var(--card);padding:25px;border:1px dashed var(--line)}@media(max-width:650px){.wrap{padding:35px 0}.plan.featured{transform:none}}
</style></head><body><header><a class="brand" href="index.php"><?= e(APP_BRAND_NAME) ?></a><nav class="nav"><a href="index.php">Home</a><?php if($user): ?><a href="dashboard.php">Dashboard</a><?php else: ?><a href="auth.php?next=subscription.php">Log in</a><?php endif; ?></nav></header><main class="wrap"><h1>Unlock more. Pay less.</h1><p class="lede">Choose a learning subscription with access to published courses that are ready to practice. Included-course counts update as new exam series are published.</p><section class="plans" aria-label="Subscription plans"><?php if($plans===[]): ?><div class="empty">No subscription plans are available yet.</div><?php else: foreach($plans as $plan): $includedSlugs=subscription_plan_course_slugs($plan,$catalog); $includedNames=array_map(static fn(string $slug): string => (string)($catalog[$slug]['title']??$slug),$includedSlugs); ?><article class="plan <?= !empty($plan['featured'])?'featured':'' ?>"><?php if(!empty($plan['featured'])):?><div class="badge">Most popular</div><?php endif; ?><h2><?= e((string)$plan['name']) ?></h2><p class="muted"><?= e((string)($plan['description']??'')) ?></p><div class="price">₹<?= number_format(((int)$plan['price_paise'])/100,2) ?><?php if((int)($plan['original_price_paise']??0)>(int)$plan['price_paise']): ?><span class="old">₹<?= number_format(((int)$plan['original_price_paise'])/100,2) ?></span><?php endif; ?></div><p class="muted">Valid for <?= (int)$plan['duration'] ?> <?= e((string)$plan['duration_unit']) ?><?= (int)$plan['duration']===1?'':'s' ?></p><ul><?php foreach((array)($plan['benefits']??[]) as $benefit): ?><li><?= e((string)$benefit) ?></li><?php endforeach; ?><li class="course-count"><?= count($includedSlugs) ?> published <?= count($includedSlugs)===1?'course':'courses' ?> currently included</li></ul><?php if($includedNames!==[]): ?><details class="course-list"><summary>View included courses</summary><p><?= e(implode(' · ',$includedNames)) ?></p><?php if(!empty($plan['all_access'])): ?><p>New eligible courses are included while your subscription is active.</p><?php endif; ?></details><?php endif; ?><?php if(in_array((string)$plan['slug'],$activeSlugs,true)): ?><div class="active">Already Active</div><?php elseif($includedSlugs===[]): ?><div class="empty">No published courses are currently available in this plan.</div><?php else: ?><a class="btn" href="subscription-checkout.php?plan=<?= e((string)$plan['slug']) ?>">Subscribe now</a><?php endif; ?></article><?php endforeach; endif; ?></section></main></body></html>
