CREATE TABLE IF NOT EXISTS blog_posts (
  id VARCHAR(48) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  excerpt TEXT NOT NULL,
  content LONGTEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  author_id VARCHAR(48) NOT NULL DEFAULT '',
  author_name VARCHAR(120) NOT NULL DEFAULT '',
  category_id VARCHAR(64) NOT NULL DEFAULT '',
  featured_image VARCHAR(1024) NOT NULL DEFAULT '',
  seo_title VARCHAR(255) NOT NULL DEFAULT '',
  seo_description TEXT NOT NULL,
  canonical_url VARCHAR(2048) NOT NULL DEFAULT '',
  og_title VARCHAR(255) NOT NULL DEFAULT '',
  og_description TEXT NOT NULL,
  published_at DATETIME DEFAULT NULL,
  scheduled_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  review_comment TEXT NOT NULL,
  INDEX idx_blog_posts_status_date (status, published_at),
  INDEX idx_blog_posts_author (author_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
